/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:6e33de80-bb4c-4708-89e0-1acccaa6c78d",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_A6nbgf2ON",
    "aws_user_pools_web_client_id": "5etan7d9nh5nrimelp7l087la8",
    "oauth": {
        "domain": "learningchineseb6b63772-b6b63772-dev.auth.ap-northeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        // "redirectSignIn": "https://learning-chinese.vercel.app/",
        // "redirectSignOut": "https://learning-chinese.vercel.app/",
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
